### ISSUE TITLE
KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND kafka 

### ISSUE THREAD

**Issue by shawon1fb** [andrechristikan/ack-nestjs-mongoose-kafka#182]
kafka.admin.service.ts  [line: 64]

to reproduce error 
`
 async onModuleInit(): Promise<void> {
        await this.connect();
        await this.helperService.delay(5000);
       try {
            await this.createTopics();
        }catch (e) {
           console.log(e);
       }
        await this.helperService.delay(5000);
    }

`

KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND kafka
    at Socket.onError (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/network/connection.js:210:23)
    ... 3 lines matching cause stack trace ...
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  retryCount: 5,
  retryTime: 8156,
  [cause]: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND kafka
      at Socket.onError (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/network/connection.js:210:23)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'kafka:9092',
    code: 'ENOTFOUND',
    [cause]: undefined
  }
}
[Nest] 8102  - 07/29/2022, 1:03:33 AM   ERROR [ClientKafka] ERROR [Connection] Response Metadata(key: 3, version: 6) {"timestamp":"2022-07-28T18:03:33.511Z","logger":"kafkajs","broker":"localhost:9092","clientId":"KAFKA_ACK-client","error":"This server does not host this topic-partition","correlationId":1,"size":125}

/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/protocol/error.js:581
  return new KafkaJSProtocolError(errorCodes.find(e => e.code === code) || unknownErrorCode(code))
         ^
KafkaJSProtocolError: This server does not host this topic-partition
    at createErrorFromCode (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/protocol/error.js:581:10)
    at Object.parse (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:55:11)
    at Connection.send (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/network/connection.js:433:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Broker.[private:Broker:sendRequest] (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/broker/index.js:875:14)
    at Broker.metadata (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/broker/index.js:177:12)
    at /Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/cluster/brokerPool.js:158:25
    at /Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/cluster/index.js:111:14
    at Cluster.refreshMetadata (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/cluster/index.js:172:5)
    at Cluster.addMultipleTargetTopics (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/cluster/index.js:230:11)
    at Object.subscribe (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/kafkajs/src/consumer/index.js:185:5)
    at async Promise.all (index 0)
    at ClientKafka.bindTopics (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/@nestjs/microservices/client/client-kafka.js:84:9)
    at ClientKafka.connect (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/node_modules/@nestjs/microservices/client/client-kafka.js:72:13)
    at KafkaProducerService.onApplicationBootstrap (/Users/shahanul/WebstormProjects/ack-microservice-nestjs-boilerplate-mongoose/src/kafka/producer/service/kafka.producer.service.ts:42:9)
    at async Promise.all (index 0)
error Command failed with exit code 1.

**Comment by shawon1fb** [comment]
docker compose file

version: '3.8'
services:
#  service:
#    build: .
#    container_name: ack
#    hostname: ack
#    ports:
#      - 3000:3000
#    networks:
#      - app-network
#    volumes:
#      - ./src/:/app/src/
#      - .env/:/app/.env
#    restart: unless-stopped
#    depends_on:
#      - mongodb
#      - zookeeper
#      - kafka
  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    networks:
      - app-network
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    networks:
      - app-network
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    volumes:
      - zookeeperdata:/bitnami:z
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    networks:
      - app-network
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_DELETE_TOPIC_ENABLE=false
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_PORT=9092
    depends_on:
      - zookeeper
    restart: unless-stopped
    volumes:
      - kafkadata:/bitnami:z
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
  kafkadata:
  zookeeperdata:

**Comment by shawon1fb** [comment]
echo dump | nc localhost 2181 | grep brokers
	/brokers/ids/1
➜  ~

**Comment by andrechristikan** [comment]
I guess that's because Kafka doesn't have/create any topics that are related to the application.
Make sure that all topics are created before running the application.

Note:
There are still bugs in Kafka's auto-create custom topics, partitioning, and replication. 
I strongly suggest to set `allowAutoTopicCreation` to be `true`
